# Generated by Django 5.0.3 on 2024-03-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='high_score',
            new_name='score',
        ),
    ]
